org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.16.5
enabled_platforms=fabric,forge

archives_base_name=jevents
mod_version=1.0.0
maven_group=org.johnfries

mod_id=jevents
mod_name=jEvents
mod_license=All Rights Reserved
mod_authors=john-fries
mod_description=Cross-loader event administration mod for organized recordings and live events.

architectury_version=1.32.68
fabric_loader_version=0.14.23
fabric_api_version=0.42.0+1.16
forge_version=1.16.5-36.2.42
